imx-base: provide right package for amd-gpu-bin if x11 is disabled
so that users don't have to customize it outside,
else we get very stranges errors like :
ERROR: Multiple versions of mesa are due to be built
(/scratch/openembedded-core/meta/recipes-graphics/mesa/mesa_git.bb
/scratch/openembedded-core/meta/recipes-graphics/mesa/mesa_9.1.6.bb).
Only one version of a given PN should be built in any given build.
You likely need to set PREFERRED_VERSION_mesa to select the correct
version or don't depend on multiple versions.

Signed-off-by: Eric Bénard <eric@eukrea.com>