linux-fslc-imx: Bump revision to 4eb20fb
This includes the following changes:

  - 4eb20fb net: fec: Call swap_buffer() prior to IP header alignment
  - 585bb72 Merge tag 'v4.1.35' into 4.1-1.0.x-imx
  - 9ca365c (tag: v4.1.35) Linux 4.1.35
  - 3b244a6 xhci: fix usb2 resume timing and races.
  - c865f98 mm: remove gup_flags FOLL_WRITE games from __get_user_pages()
  - 4edf04a timekeeping: Fix __ktime_get_fast_ns() regression
  - 486eeb6 time: Add cycles to nanoseconds translation
  - a4a6bb0 iwlwifi: mvm: fix default disabled aggs in sta
  - 32da3e0 iwlwifi: dvm: remove ADD_STA prints relying on station ID
  - 067952c iwlwifi: dvm: move ADD_STA response handling to sync command
  - bf8308e iwlwifi: mvm: Configure agg. queue before assigning it to STA
  - 91473db Linux 4.1.34
  - 5699106 openrisc: fix the fix of copy_from_user()
  - 2abcdcc avr32: fix 'undefined reference to `___copy_from_user'
  - e22ff45 fix memory leaks in tracing_buffers_splice_read()
  - abd91e8 tracing: Move mutex to protect against resetting of seq data
  - 7d0e577 MIPS: SMP: Fix possibility of deadlock when bringing CPUs online
  - 94b73f6 MIPS: Fix pre-r6 emulation FPU initialisation
  - 3b3f2e9 btrfs: ensure that file descriptor used with subvol ioctls is a dir
  - 01e893a fix fault_in_multipages_...() on architectures with no-op access_ok()
  - 8b91555 ocfs2: fix start offset to ocfs2_zero_range_for_truncate()
  - fa22b5b fanotify: fix list corruption in fanotify_get_response()
  - 2ea570f fsnotify: add a way to stop queueing events on group shutdown
  - 7853bc7 autofs: use dentry flags to block walks during expire
  - 8e625a4 autofs races
  - fe8bd72 ocfs2/dlm: fix race between convert and migration
  - 9cbf61a MIPS: Avoid a BUG warning during prctl(PR_SET_FP_MODE, ...)
  - fc6e4ce can: flexcan: fix resume function
  - a286d16 drm: Only use compat ioctl for addfb2 on X86/IA64
  - ca3fea0 fix iov_iter_fault_in_readable()
  - 507e166 USB: change bInterval default to 10 ms
  - 319fe11 fix minor infoleak in get_user_ex()
  - 1e8727f avr32: fix copy_from_user()
  - d6dd6bf microblaze: fix __get_user()
  - 9159bc0 microblaze: fix copy_from_user()
  - c6ab30d m32r: fix __get_user()
  - 59dd93e blackfin: fix copy_from_user()
  - 09d5ea2 sparc32: fix copy_from_user()
  - 0fe6f5c sh: fix copy_from_user()
  - dbff5b3 sh64: failing __get_user() should zero
  - 8f74a7d score: fix copy_from_user() and friends
  - 382c91f score: fix __get_user/get_user
  - 8e5c49f s390: get_user() should zero on failure
  - 5a1bd17 ppc32: fix copy_from_user()
  - f39be7f parisc: fix copy_from_user()
  - cc148fe openrisc: fix copy_from_user()
  - acc2bdc nios2: fix __get_user()
  - f485933 nios2: copy_from_user() should zero the tail of destination
  - da879e3 mn10300: copy_from_user() should zero on access_ok() failure...
  - c6f5ace mn10300: failing __get_user() and get_user() should zero
  - 34c4640 mips: copy_from_user() must zero the destination on access_ok() failure
  - 57dcb60 ARC: uaccess: get_user to zero out dest in cause of fault
  - f3d57a7 metag: copy_from_user() should zero the destination on access_ok() failure
  - 5b6def3 ia64: copy_from_user() should zero the destination on access_ok() failure
  - 4661786 hexagon: fix strncpy_from_user() error return
  - bd2f050 frv: fix clear_user()
  - e0176ee cris: buggered copy_from_user/copy_to_user/clear_user
  - e73af4f asm-generic: make get_user() clear the destination on errors
  - a4b7778 asm-generic: {get,put}_user ptr argument evaluate only 1 time
  - adb108b nl80211: validate number of probe response CSA counters
  - 14279ce MIPS: Add a missing ".set pop" in an early commit
  - fcbe53d genirq: Provide irq_gc_{lock_irqsave,unlock_irqrestore}() helpers
  - ebed93d MIPS: paravirt: Fix undefined reference to smp_bootstrap
  - 3e81f02 crypto: arm64/aes-ctr - fix NULL dereference in tail processing
  - 3b7df38 crypto: arm/aes-ctr - fix NULL dereference in tail processing
  - a55614f crypto: skcipher - Fix blkcipher walk OOM crash
  - ce2fe08 USB: serial: simple: add support for another Infineon flashloader
  - f40afee NFSv4.1: Fix the CREATE_SESSION slot number accounting
  - 41beb77 fscrypto: require write access to mount to set encryption policy
  - 08ac15d asm-generic: make copy_from_user() zero the destination properly
  - ca79a8d alpha: fix copy_from_user()
  - f2ec3a1 arm64: spinlocks: implement smp_mb__before_spinlock() as smp_mb()
  - 323d534 kvm-arm: Unmap shadow pagetables properly
  - 32eb86c usb: chipidea: udc: fix NULL ptr dereference in isr_setup_status_phase
  - 4bfeb58 ARM: dts: STiH410: Handle interconnect clock required by EHCI/OHCI (USB)
  - 1c33cc0 ALSA: rawmidi: Fix possible deadlock with virmidi registration
  - d14b394 ALSA: timer: Fix zero-division by continue of uninitialized instance
  - bc84b38 ALSA: timer: Call notifier in the same spinlock
  - 631f063 xhci: fix null pointer dereference in stop command timeout function
  - 7b6ea25 powerpc/mm: Don't alias user region to other regions below PAGE_OFFSET
  - b8e5110 crypto: cryptd - initialize child shash_desc on import
  - 81e6db1 ipv6: addrconf: fix dev refcont leak when DAD failed
  - 12ebbc2 Btrfs: remove root_log_ctx from ctx list before btrfs_sync_log returns
  - c2aca6b drm: atmel-hlcdc: Fix vertical scaling
  - 12c68a9 ovl: fix workdir creation
  - 8af2ce0 usb: renesas_usbhs: fix clearing the {BRDY,BEMP}STS condition
  - 431d09f sched/core: Fix a race between try_to_wake_up() and a woken up task
  - 1ea35b9 iio: accel: kxsd9: Fix scaling bug
  - 193eb8f ALSA: timer: fix NULL pointer dereference in read()/ioctl() race
  - 854a40f ALSA: fireworks: accessing to user space outside spinlock
  - 82ae68a ARM: imx6: add missing BM_CLPCR_BYPASS_PMIC_READY setting for imx6sx
  - 6558ce6 ALSA: hda - Enable subwoofer on Dell Inspiron 7559
  - 7b7cc69 ALSA: usb-audio: Add sample rate inquiry quirk for B850V3 CP2114
  - 6138d59 ALSA: timer: fix NULL pointer dereference on memory allocation failure
  - 2350481 ALSA: timer: fix division by zero after SNDRV_TIMER_IOCTL_CONTINUE
  - 8773752 ARM: kirkwood: ib62x0: fix size of u-boot environment partition
  - 7933dd8 fuse: direct-io: don't dirty ITER_BVEC pages
  - bb5c68e ath9k: fix using sta->drv_priv before initializing it
  - c3e7a0e bus: arm-ccn: Fix XP watchpoint settings bitmask
  - b9d45ce bus: arm-ccn: Do not attempt to configure XPs for cycle counter
  - 0dd4c68 scsi: fix upper bounds check of sense key in scsi_sense_key_string()
  - cfad3a5 Revert "wext: Fix 32 bit iwpriv compatibility issue with 64 bit Kernel"
  - bd2d704 ARM: OMAP3: hwmod data: Add sysc information for DSI
  - 3b23ff9 MIPS: KVM: Check for pfn noslot case

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>