imx-test: Ensures kernel is installed before building scripts
The imx-test builds a kernel module, as one of the utilities used for
testing. The module relies on the kernel to be installed before it is
able to build the scripts necessary for the build to succeed.

Due the new kernel build infrastructure and the lack of the sstate
management over the kernel source, a explicit dependency on do_install
of kernel needs to be done.

This fixes following failure:

,----
| .../.../module_test/mxc_sdma_mem_test.c:21:27: fatal error: linux/version.h: No such file or directory
|  #include <linux/version.h>
|                            ^
| compilation terminated.
| make[4]: *** [.../.../module_test/mxc_sdma_mem_test.o] Error 1
| make[3]: *** [_module_.../.../module_test] Error 2
| make[2]: *** [sub-make] Error 2
| make[2]: Leaving directory `.../build-framebuffer/tmp/sysroots/imx53qsb/usr/src/kernel'
| make[1]: *** [all] Error 2
| make[1]: Leaving directory `.../.../module_test'
| make: *** [module_test] Error 2
`----

Change-Id: I0ebdfce4483d64fed4afe52c09d8e1d31d9374bb
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>