linux-imx (3.0.35): perf tools: Fix build against newer glibc
Upstream glibc commit 295e904 added a definition for __attribute_const__
to cdefs.h.  This causes the following error when building perf:

util/include/linux/compiler.h:8:0: error: "__attribute_const__"
redefined [-Werror] /usr/include/sys/cdefs.h:226:0: note: this is the
location of the previous definition

Wrap __attribute_const__ in #ifndef as we do for __always_inline.

Change-Id: I0d12b349826162117b7708f79b6cac14621bcb30
Signed-off-by: Daiane Angolini <daiane.angolini@freescale.com>